#!/bin/bash
clear
echo ""

tput setaf 2 ; tput bold ; echo "DROPBEAR: ALTERNATIVO" ; tput sgr0

echo "$(tput bold) ESCOGE UNA DISTRIBUCION: $(tput sgr0)"

echo ""

echo "1. Ubuntu e Debian"

echo "2. CentOs 7"

echo "3. CentOs 6: 64bits"

echo "4. Salir"

echo ""

echo -n "Escoge una opcion? "

read opcao

case $opcao in

1)
clear
echo ""
tput setaf 2 ; tput bold ; echo "Instalando Dropbear" ; tput sgr0
sleep 2

apt-get install dropbear 1>/dev/null 2>/dev/null

rm -rf /etc/default/dropbear 1>/dev/null 2>/dev/null

echo "/bin/false" >> /etc/shells

echo ""

echo "Cual puerto deseas agregar a Dropbear ?"
read port

echo "NO_START=0" >> /etc/default/dropbear
echo "DROPBEAR_PORT=$port" >> /etc/default/dropbear
echo "DROPBEAR_EXTRA_ARGS='-p $port'" >> /etc/default/dropbear

service dropbear start 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null

echo "puerto $port agregado"

echo "$(tput bold) DROPBEAR CONFIGURADO. $(tput sgr0)"


;;

2)
clear
echo ""
tput setaf 2 ; tput bold ; echo "Dropbear PowerMX" ; tput sgr0
sleep 2

yum update -y 1>/dev/null 2>/dev/null
yum upgrade -y 1>/dev/null 2>/dev/null

rpm -Uvh http://ftp-stud.hs-esslingen.de/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm 1>/dev/null 2>/dev/null 

yum -y install dropbear 1>/dev/null 2>/dev/null

rm -rf /etc/sysconfig/dropbear 1>/dev/null 2>/dev/null

echo "Cual puerto deseas agregar a Dropbear ?"
read port

echo "OPTIONS='-p $port'" >> /etc/sysconfig/dropbear

chkconfig dropbear on 1>/dev/null 2>/dev/null 
systemctl enable dropbear.service 1>/dev/null 2>/dev/null 
systemctl start dropbear.service 1>/dev/null 2>/dev/null 

echo "/bin/false" >> /etc/shells

systemctl restart dropbear.service 1>/dev/null 2>/dev/null

echo "porta $port adicionada"

echo "$(tput bold) DROPBEAR CONFIGURADO. $(tput sgr0)"

;;

3)
clear
echo ""
tput setaf 2 ; tput bold ; echo "Dropbear" ; tput sgr0
sleep 2
yum update -y 1>/dev/null 2>/dev/null
yum upgrade -y 1>/dev/null 2>/dev/null

rpm -Uvh http://ftp-stud.hs-esslingen.de/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

yum -y install dropbear 1>/dev/null 2>/dev/null

rm -rf /etc/init.d/dropbear 1>/dev/null 2>/dev/null

echo "Cual puerto deseas agregar a Dropbear ?"
read port

echo "OPTIONS='-p $port'" >> /etc/init.d/dropbear

service dropbear start 1>/dev/null 2>/dev/null 

echo "/bin/false" >> /etc/shells

service dropbear restart 1>/dev/null 2>/dev/null

echo "puerto $port agregado"

echo "$(tput bold) DROPBEAR CONFIGURADO. $(tput sgr0)"

;;

4)
echo " Saliendo..."
exit
;;
esac
rm install
